# Generated by Django 2.2 on 2022-11-15 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0004_auto_20221114_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartlist',
            old_name='cart1_id',
            new_name='cart_id',
        ),
    ]
